PRAGMA foreign_keys=off;

BEGIN TRANSACTION;

ALTER TABLE products RENAME TO _products_old;


CREATE TABLE products
(
"id" INTEGER PRIMARY KEY,
"code" INTEGER,
"url" TEXT,
"creator" TEXT,
"created_t" INTEGER,
"last_modified_t" INTEGER,
"product_name" TEXT,
"generic_name" TEXT,
"quantity" TEXT,
"packaging" TEXT,
"packaging_tags" TEXT,
"packaging_text" TEXT,
"brands" TEXT,
"brands_tags" TEXT,
"categories" TEXT,
"categories_tags" TEXT,
"origins" TEXT,
"origins_tags" TEXT,
"manufacturing_places" TEXT,
"manufacturing_places_tags" TEXT,
"labels" TEXT,
"labels_tags" TEXT,
"emb_codes" TEXT,
"emb_codes_tags" TEXT,
"cities" REAL,
"cities_tags" TEXT,
"purchase_places" TEXT,
"stores" TEXT,
"countries" TEXT,
"ingredients_text" TEXT,
"allergens" TEXT,
"allergens_tags" TEXT,
"traces" TEXT,
"traces_tags" TEXT,
"serving_size" TEXT,
"serving_quantity" REAL,
"no_nutriments" REAL,
"additives_n" REAL,
"additives_tags" TEXT,
"ingredients_from_palm_oil_n" REAL,
"ingredients_from_palm_oil" REAL,
"ingredients_from_palm_oil_tags" TEXT,
"ingredients_that_may_be_from_palm_oil_n" REAL,
"ingredients_that_may_be_from_palm_oil" REAL,
"ingredients_that_may_be_from_palm_oil_tags" TEXT,
"nutriscore_score" REAL,
"nutriscore_grade" TEXT,
"nova_group" REAL,
"pnns_groups_1" TEXT,
"pnns_groups_2" TEXT,
"states" TEXT,
"brand_owner" TEXT,
"main_category" TEXT,
"image_url" TEXT,
"image_small_url" TEXT,
"image_front_url" TEXT,
"image_front_small_url" TEXT,
"image_ingredients_url" TEXT,
"image_ingredients_small_url" TEXT,
"image_nutrition_url" TEXT,
"image_nutrition_small_url" TEXT,
"energy-kj_100g" REAL,
"energy-kcal_100g" REAL,
"energy_100g" REAL,
"energy-from-fat_100g" REAL,
"fat_100g" REAL,
"saturated-fat_100g" REAL,
"-butyric-acid_100g" REAL,
"-caproic-acid_100g" REAL,
"-caprylic-acid_100g" REAL,
"-capric-acid_100g" REAL,
"-lauric-acid_100g" REAL,
"-myristic-acid_100g" REAL,
"-palmitic-acid_100g" REAL,
"-stearic-acid_100g" REAL,
"-arachidic-acid_100g" REAL,
"-behenic-acid_100g" REAL,
"-lignoceric-acid_100g" REAL,
"-cerotic-acid_100g" REAL,
"-montanic-acid_100g" REAL,
"-melissic-acid_100g" REAL,
"monounsaturated-fat_100g" REAL,
"polyunsaturated-fat_100g" REAL,
"omega-3-fat_100g" REAL,
"-alpha-linolenic-acid_100g" REAL,
"-eicosapentaenoic-acid_100g" REAL,
"-docosahexaenoic-acid_100g" REAL,
"omega-6-fat_100g" REAL,
"-linoleic-acid_100g" REAL,
"-arachidonic-acid_100g" REAL,
"-gamma-linolenic-acid_100g" REAL,
"-dihomo-gamma-linolenic-acid_100g" REAL,
"omega-9-fat_100g" REAL,
"-oleic-acid_100g" REAL,
"-elaidic-acid_100g" REAL,
"-gondoic-acid_100g" REAL,
"-mead-acid_100g" REAL,
"-erucic-acid_100g" REAL,
"-nervonic-acid_100g" REAL,
"trans-fat_100g" REAL,
"cholesterol_100g" REAL,
"carbohydrates_100g" REAL,
"sugars_100g" REAL,
"-sucrose_100g" REAL,
"-glucose_100g" REAL,
"-fructose_100g" REAL,
"-lactose_100g" REAL,
"-maltose_100g" REAL,
"-maltodextrins_100g" REAL,
"starch_100g" REAL,
"polyols_100g" REAL,
"fiber_100g" REAL,
"-soluble-fiber_100g" REAL,
"-insoluble-fiber_100g" REAL,
"proteins_100g" REAL,
"casein_100g" REAL,
"serum-proteins_100g" REAL,
"nucleotides_100g" REAL,
"salt_100g" REAL,
"sodium_100g" REAL,
"alcohol_100g" REAL,
"vitamin-a_100g" REAL,
"beta-carotene_100g" REAL,
"vitamin-d_100g" REAL,
"vitamin-e_100g" REAL,
"vitamin-k_100g" REAL,
"vitamin-c_100g" REAL,
"vitamin-b1_100g" REAL,
"vitamin-b2_100g" REAL,
"vitamin-pp_100g" REAL,
"vitamin-b6_100g" REAL,
"vitamin-b9_100g" REAL,
"folates_100g" REAL,
"vitamin-b12_100g" REAL,
"biotin_100g" REAL,
"pantothenic-acid_100g" REAL,
"silica_100g" REAL,
"bicarbonate_100g" REAL,
"potassium_100g" REAL,
"chloride_100g" REAL,
"calcium_100g" REAL,
"phosphorus_100g" REAL,
"iron_100g" REAL,
"magnesium_100g" REAL,
"zinc_100g" REAL,
"copper_100g" REAL,
"manganese_100g" REAL,
"fluoride_100g" REAL,
"selenium_100g" REAL,
"chromium_100g" REAL,
"molybdenum_100g" REAL,
"iodine_100g" REAL,
"caffeine_100g" REAL,
"taurine_100g" REAL,
"ph_100g" REAL,
"fruits-vegetables-nuts_100g" REAL,
"fruits-vegetables-nuts-dried_100g" REAL,
"fruits-vegetables-nuts-estimate_100g" REAL,
"collagen-meat-protein-ratio_100g" REAL,
"cocoa_100g" REAL,
"chlorophyl_100g" REAL,
"carbon-footprint_100g" REAL,
"carbon-footprint-from-meat-or-fish_100g" REAL,
"nutrition-score-fr_100g" REAL,
"nutrition-score-uk_100g" REAL,
"glycemic-index_100g" REAL,
"water-hardness_100g" REAL,
"choline_100g" REAL,
"phylloquinone_100g" REAL,
"beta-glucan_100g" REAL,
"inositol_100g" REAL,
"carnitine_100g" REAL
);

INSERT INTO products (
    "code",
"url",
"creator",
"created_t",
"last_modified_t",
"product_name",
"generic_name",
"quantity",
"packaging",
"packaging_tags",
"packaging_text",
"brands",
"brands_tags",
"categories",
"categories_tags",
"origins",
"origins_tags",
"manufacturing_places",
"manufacturing_places_tags",
"labels",
"labels_tags",
"emb_codes",
"emb_codes_tags",
"cities",
"cities_tags",
"purchase_places",
"stores",
"countries",
"ingredients_text",
"allergens",
"allergens_tags",
"traces",
"traces_tags",
"serving_size",
"serving_quantity",
"no_nutriments",
"additives_n",
"additives_tags",
"ingredients_from_palm_oil_n",
"ingredients_from_palm_oil",
"ingredients_from_palm_oil_tags",
"ingredients_that_may_be_from_palm_oil_n",
"ingredients_that_may_be_from_palm_oil",
"ingredients_that_may_be_from_palm_oil_tags",
"nutriscore_score",
"nutriscore_grade",
"nova_group",
"pnns_groups_1",
"pnns_groups_2",
"states",
"brand_owner",
"main_category",
"image_url",
"image_small_url",
"image_front_url",
"image_front_small_url",
"image_ingredients_url",
"image_ingredients_small_url",
"image_nutrition_url",
"image_nutrition_small_url",
"energy-kj_100g",
"energy-kcal_100g",
"energy_100g",
"energy-from-fat_100g",
"fat_100g",
"saturated-fat_100g",
"-butyric-acid_100g",
"-caproic-acid_100g",
"-caprylic-acid_100g",
"-capric-acid_100g",
"-lauric-acid_100g",
"-myristic-acid_100g",
"-palmitic-acid_100g",
"-stearic-acid_100g",
"-arachidic-acid_100g",
"-behenic-acid_100g",
"-lignoceric-acid_100g",
"-cerotic-acid_100g",
"-montanic-acid_100g",
"-melissic-acid_100g",
"monounsaturated-fat_100g",
"polyunsaturated-fat_100g",
"omega-3-fat_100g",
"-alpha-linolenic-acid_100g",
"-eicosapentaenoic-acid_100g",
"-docosahexaenoic-acid_100g",
"omega-6-fat_100g",
"-linoleic-acid_100g",
"-arachidonic-acid_100g",
"-gamma-linolenic-acid_100g",
"-dihomo-gamma-linolenic-acid_100g",
"omega-9-fat_100g",
"-oleic-acid_100g",
"-elaidic-acid_100g",
"-gondoic-acid_100g",
"-mead-acid_100g",
"-erucic-acid_100g",
"-nervonic-acid_100g",
"trans-fat_100g",
"cholesterol_100g",
"carbohydrates_100g",
"sugars_100g",
"-sucrose_100g",
"-glucose_100g",
"-fructose_100g",
"-lactose_100g",
"-maltose_100g",
"-maltodextrins_100g",
"starch_100g",
"polyols_100g",
"fiber_100g",
"-soluble-fiber_100g",
"-insoluble-fiber_100g",
"proteins_100g",
"casein_100g",
"serum-proteins_100g",
"nucleotides_100g",
"salt_100g",
"sodium_100g",
"alcohol_100g",
"vitamin-a_100g",
"beta-carotene_100g",
"vitamin-d_100g",
"vitamin-e_100g",
"vitamin-k_100g",
"vitamin-c_100g",
"vitamin-b1_100g",
"vitamin-b2_100g",
"vitamin-pp_100g",
"vitamin-b6_100g",
"vitamin-b9_100g",
"folates_100g",
"vitamin-b12_100g",
"biotin_100g",
"pantothenic-acid_100g",
"silica_100g",
"bicarbonate_100g",
"potassium_100g",
"chloride_100g",
"calcium_100g",
"phosphorus_100g",
"iron_100g",
"magnesium_100g",
"zinc_100g",
"copper_100g",
"manganese_100g",
"fluoride_100g",
"selenium_100g",
"chromium_100g",
"molybdenum_100g",
"iodine_100g",
"caffeine_100g",
"taurine_100g",
"ph_100g",
"fruits-vegetables-nuts_100g",
"fruits-vegetables-nuts-dried_100g",
"fruits-vegetables-nuts-estimate_100g",
"collagen-meat-protein-ratio_100g",
"cocoa_100g",
"chlorophyl_100g",
"carbon-footprint_100g",
"carbon-footprint-from-meat-or-fish_100g",
"nutrition-score-fr_100g",
"nutrition-score-uk_100g",
"glycemic-index_100g",
"water-hardness_100g",
"choline_100g",
"phylloquinone_100g",
"beta-glucan_100g",
"inositol_100g",
"carnitine_100g"
    )
  SELECT
    "code",
"url",
"creator",
"created_t",
"last_modified_t",
"product_name",
"generic_name",
"quantity",
"packaging",
"packaging_tags",
"packaging_text",
"brands",
"brands_tags",
"categories",
"categories_tags",
"origins",
"origins_tags",
"manufacturing_places",
"manufacturing_places_tags",
"labels",
"labels_tags",
"emb_codes",
"emb_codes_tags",
"cities",
"cities_tags",
"purchase_places",
"stores",
"countries",
"ingredients_text",
"allergens",
"allergens_tags",
"traces",
"traces_tags",
"serving_size",
"serving_quantity",
"no_nutriments",
"additives_n",
"additives_tags",
"ingredients_from_palm_oil_n",
"ingredients_from_palm_oil",
"ingredients_from_palm_oil_tags",
"ingredients_that_may_be_from_palm_oil_n",
"ingredients_that_may_be_from_palm_oil",
"ingredients_that_may_be_from_palm_oil_tags",
NULLIF("nutriscore_score", ''),
"nutriscore_grade",
"nova_group",
"pnns_groups_1",
"pnns_groups_2",
"states",
"brand_owner",
"main_category",
"image_url",
"image_small_url",
"image_front_url",
"image_front_small_url",
"image_ingredients_url",
"image_ingredients_small_url",
"image_nutrition_url",
"image_nutrition_small_url",
"energy-kj_100g",
"energy-kcal_100g",
"energy_100g",
"energy-from-fat_100g",
"fat_100g",
"saturated-fat_100g",
"-butyric-acid_100g",
"-caproic-acid_100g",
"-caprylic-acid_100g",
"-capric-acid_100g",
"-lauric-acid_100g",
"-myristic-acid_100g",
"-palmitic-acid_100g",
"-stearic-acid_100g",
"-arachidic-acid_100g",
"-behenic-acid_100g",
"-lignoceric-acid_100g",
"-cerotic-acid_100g",
"-montanic-acid_100g",
"-melissic-acid_100g",
"monounsaturated-fat_100g",
"polyunsaturated-fat_100g",
"omega-3-fat_100g",
"-alpha-linolenic-acid_100g",
"-eicosapentaenoic-acid_100g",
"-docosahexaenoic-acid_100g",
"omega-6-fat_100g",
"-linoleic-acid_100g",
"-arachidonic-acid_100g",
"-gamma-linolenic-acid_100g",
"-dihomo-gamma-linolenic-acid_100g",
"omega-9-fat_100g",
"-oleic-acid_100g",
"-elaidic-acid_100g",
"-gondoic-acid_100g",
"-mead-acid_100g",
"-erucic-acid_100g",
"-nervonic-acid_100g",
"trans-fat_100g",
"cholesterol_100g",
"carbohydrates_100g",
"sugars_100g",
"-sucrose_100g",
"-glucose_100g",
"-fructose_100g",
"-lactose_100g",
"-maltose_100g",
"-maltodextrins_100g",
"starch_100g",
"polyols_100g",
"fiber_100g",
"-soluble-fiber_100g",
"-insoluble-fiber_100g",
"proteins_100g",
"casein_100g",
"serum-proteins_100g",
"nucleotides_100g",
"salt_100g",
"sodium_100g",
"alcohol_100g",
"vitamin-a_100g",
"beta-carotene_100g",
"vitamin-d_100g",
"vitamin-e_100g",
"vitamin-k_100g",
"vitamin-c_100g",
"vitamin-b1_100g",
"vitamin-b2_100g",
"vitamin-pp_100g",
"vitamin-b6_100g",
"vitamin-b9_100g",
"folates_100g",
"vitamin-b12_100g",
"biotin_100g",
"pantothenic-acid_100g",
"silica_100g",
"bicarbonate_100g",
"potassium_100g",
"chloride_100g",
"calcium_100g",
"phosphorus_100g",
"iron_100g",
"magnesium_100g",
"zinc_100g",
"copper_100g",
"manganese_100g",
"fluoride_100g",
"selenium_100g",
"chromium_100g",
"molybdenum_100g",
"iodine_100g",
"caffeine_100g",
"taurine_100g",
"ph_100g",
"fruits-vegetables-nuts_100g",
"fruits-vegetables-nuts-dried_100g",
"fruits-vegetables-nuts-estimate_100g",
"collagen-meat-protein-ratio_100g",
"cocoa_100g",
"chlorophyl_100g",
"carbon-footprint_100g",
"carbon-footprint-from-meat-or-fish_100g",
NULLIF("nutrition-score-fr_100g", ''),
NULLIF("nutrition-score-uk_100g", ''),
"glycemic-index_100g",
"water-hardness_100g",
"choline_100g",
"phylloquinone_100g",
"beta-glucan_100g",
"inositol_100g",
"carnitine_100g"
  FROM _products_old;

COMMIT;

PRAGMA foreign_keys=on;