# Generated by Django 3.1.3 on 2020-11-28 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_to_node',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product_to_node',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Spotted_On',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('product_node_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotted_on', to='api.product_to_node')),
            ],
        ),
        migrations.CreateModel(
            name='Not_Spotted_On',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('product_node_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_spotted_on', to='api.product_to_node')),
            ],
        ),
    ]
