# Generated by Django 3.1.3 on 2020-12-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_producttonode_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttonode',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.products'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='producttonode',
            unique_together={('product', 'node')},
        ),
        migrations.RemoveField(
            model_name='producttonode',
            name='code',
        ),
    ]
